language: php
php:
  - 5.5
  - 5.4
  - hhvm
before_install:
  - php /home/travis/.phpenv/versions/5.5/bin/composer.phar self-update
install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install